### ISSUE TITLE
Errors on windows [libclang related]

### ISSUE THREAD

**Issue by niosus** [niosus/EasyClangComplete#4]
When running on windows the plugin cannot find libclang with the error `EasyClangComplete: function 'clang_CXXField_isMutable' `. Moving the discussions about this here from issue #1

**Comment by niosus** [comment]
@canfoderiskii I decided to open a separate issue on the error on windows. I have tried to install clang on windows and I need some more input from your side I guess. Are you using MSVC to provide you with actual c/c++ language sources? Or are you at MinGW? Is there something else?

**Comment by canfoderiskii** [comment]
@niosus to make clang run, just make sure clang.exe can be found in PATH. When installing clang from official installer, the installer will ask you if you'd like add the llvm program location to PATH. If u missed that, u can do it manually. Just add the "bin" folder path of LLVM into PATH, for me, that path is "D:\devel\LLVM\bin"

I don't think MSVC or MinGW is necessary for running clang.

**Comment by canfoderiskii** [comment]
to check if clang can run successfully, just open a cmd or powershell, type in "clang" and see if there is message that comes from clang.

**Comment by niosus** [comment]
Yeah, I can find `clang.exe` both in `cmd` and `powershell`, but I am unable to build even a small test program with it. It cannot find any system includes like `stdio.h` for example. Thus, I cannot test my plugin on it. So my question was more on the steps needed to actually compile something with clang.

**Comment by canfoderiskii** [comment]
@niosus sorry for my misunderstanding, I haven't tried compiling clang yet, i'm sorry i can't help you with that.

I'm a C programmer for some embedded platfom with different ISA, so actually I haven't paid so much attention to compiling clang but some of its basic usage.

Maybe i will check out the cmake setting of clang source as a start.

**Comment by niosus** [comment]
Oh, no I don't mean to compile clang on Windows. That is definitely out of the scope. What I want to do is essentially (from powershell):
```
clang++ test.cpp
```
And I cannot do this. I know that clang is in the PATH and the only problem is that it cannot find the linker now. (which is one from the visual studio currently). I just wanted to try to build at least a small `hello world` example with `clang` on windows before trying to debug the plugin.

How are you using clang in your development?

**Comment by canfoderiskii** [comment]
@niosus actually i don't use clang in my development, i use other compilers, not even GCC. If I have to build some desktop program, i usually choose GCC. 
So, as you can see, i haven't tried compiling using clang yet, sorry for that. As i use sublime text as my primary editor and found that clang can do magical things to help me code more quickly few days ago, then i started to learn some knowledge about clang to fulfill my personal curiosity. 

I did some search, to compile successfully, clang needs backend tools, because clang is not a complete toolchain. Let me dig more.

**Comment by canfoderiskii** [comment]
To my understanding, to analyse syntax only needs clang itsself, as a compiler. Why we need the linker to link object file?

**Comment by canfoderiskii** [comment]
It seems that if we want to use clang to successfully build some code, we have to build clang & llvm first.
Check this out:
http://clang.llvm.org/get_started.html#buildWindows
http://stackoverflow.com/questions/9427356/how-to-compile-clang-on-windows

**Comment by niosus** [comment]
@canfoderiskii you are actually correct. I think I will just try to run my plugin then with just the clang compiler. We really need no linker here. Thanks for all the search. :)

**Comment by canfoderiskii** [comment]
you're welcome.

**Comment by niosus** [comment]
Ok, there is progress. I have fixed a couple of stupid bugs in the code and it loads the completions at least once :) The problem is that if I try to get a little bit faster with typing I bump into an error in visual c++ that eventually kills the plugin host :) I will add mutexes around in my code and will see if it fixes this behavior.

**Comment by niosus** [comment]
@canfoderiskii uh, this issue is killing me :) I have spent too much time on it, really. My current state is the following. On my windows machine with clang 3.8 installed the `plugin_host` of sublime text stops working upon completion. But only sometimes, when I use `reparse()` python function or `clangComplete()`. These both are from clang official pythong bindings and I am sure the version of the library is picked correctly now. Sometimes the package shows another error which is caused by a line in llvm source:
```
assert(acquired && "Concurrent access to ASTUnit!");
```
The thing that bothers me is that I do not access the libclang from multiple threads and I never do this simultaneously. So I am pretty confused by now. 

Could you test the current version on your side? If you have the same behavior, then probably it is not that easy to use libclang for autocompletion on Windows :)

**Comment by canfoderiskii** [comment]
@niosus Okay, I'll update and give it a try sometime. Thank you for the upgrade. But i'm sorry i can't help you to solve the code error for now, because I'm totally not familiar with developing sublime text plugin or clang.

**Comment by niosus** [comment]
no problem at all! You are helping enough :) Thanks!

**Comment by niosus** [comment]
I definitely need help from somebody who uses windows as a daily driver. 

Short summary.
- Installed MSVC c++
- Installed latest clang
- getting concurrency related errors when using this plugin.

If you want to help try the plugin and tell me if you can reproduce the error of `plugin_host` hanging.
@pl-ca if you have a couple of minutes, could you try this out?

**Comment by pl-ca** [comment]
I am no Windows expert, but I will give it a shot this weekend and see what I can find!

**Comment by niosus** [comment]
Thanks @pl-ca ! I don't want to put much pressure on you. I just want some confirmation that this happens not only on my machine. Then I will dig deeper. :)

**Comment by canfoderiskii** [comment]
@niosus  I tried your latest code. I didn't encountered the plugin_host stopping problem. But i still got this error message:
_EasyClangComplete: function 'clang_CXXField_isMutable' not found. Please ensure that your python bindings are compatible with your libclang.so version._

**Comment by niosus** [comment]
ok, thanks a lot! I will wait for @pl-ca  to also try this out and then will try to find out what is going on. Thanks for the effort!

**Comment by pl-ca** [comment]
Hi @niosus, I have installed your plugin, for which I had to add the following line to have it run

```diff
@@ -14,6 +14,7 @@ import time
import importlib
import sys
import os.path as path
+import imp 

from threading import Thread
```

Then I tried to trigger auto-completion and it did not appear to work, I may be missing something as I'm not too sure how your plug-in is working.

I get the following output in console with `"verbose" : true`.

```
EasyClangComplete: view has no completer
EasyClangComplete: compilation started.
EasyClangComplete: [WinError 126] The specified module could not be found. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
EasyClangComplete: starting async auto_complete at pos: 85
```

Otherwise I'm on Windows 10 with clang version 3.6.0 installed from its website.

**Comment by niosus** [comment]
Thanks @pl-ca 
I think I have that line in the master already.

As for the error. It is related to libclang, but this seems to be Windows specific, so I will have to find out. I don't think the `Config.set_library_path()` is actually a sound advice. :) I will try to install clang 3.6.0 and test it again. 

It is annoying that we have 3 Windows setups and 3 different errors. :) Thanks anyway. 

I think, I will just use clang binary instead of libclang for Windows, just as you do. Although, this behavior is strange.

**Comment by simonhaenisch** [comment]
![capture](https://cloud.githubusercontent.com/assets/3410759/14984928/82347d9c-1145-11e6-8122-1915615ef315.PNG)

I see this error message window when triggering an auto complete (I have your `auto_complete_triggers` example settings in my syntax specific settings). I installed LLVM 3.8 - Clang for Windows (64-bit).

After my plugins loaded, I get this info in console:
```
    cannot get default cindex with error: No module named 'clang'
    using bundled one: EasyClangComplete.clang.cindex38
```

Pressing Abort stops the Sublime Text plugin host. If you need any more info, let me know.

**Comment by niosus** [comment]
@simonhaenisch thanks for the info! At least this is the same issue that I seem to have on windows. Can you also enable "verbose: true" in plugin settings?

**Comment by simonhaenisch** [comment]
I have verbose flag set, but didn't get any output. Now I updated to your current master, but it's still the same error.

When I set `"use_libclang": false` (and restart Sublime) and trigger a completion, it works as long as there is no error in the file. When I i.e. remove a semicolon somewhere, I get this in console:
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "C:\Users\%username%\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\clang_bin_complete.py", line 205, in complete
    complete_results)
  File "C:\Users\%username%\AppData\Roaming\Sublime Text 3\Packages\EasyClangComplete\plugin\clang_bin_complete.py", line 270, in _process_completions
    comp_dict = pos_search.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

This is expected, I guess?

When a completion doesn't work because a file can't be found (not in include dirs), then I just get an empty line as output in the console. Are include directories recursive (do they include all sub-directories)?

Another thing: I can't get completions to work for OpenCV, could this be, because the headers are `.hpp` instead of `.h`?

**Comment by niosus** [comment]
@simonhaenisch oops. No the error is not expected, but is easy to fix. Will do during the week. I have just added support for using clang binary instead of libclang and haven't even closed the issue, so no proper testing has been done. It will be done soon and then you should not experience this error. I will create an issue for it for now.

It is strange that you see no output in the console even with verbose set to true. I will also move it to a separate issue.

If one of the include files is not present it should have absolutely no consequences on autocompletion as clang is able to handle this. I believe it is connected to the exceptions you see. I will tell you when you could test it again. :)

It works for OpenCV for me, but I only tried it with libclang, need to test it with clang binary too.

Thanks for reporting all of these! If you find something else - feel free to fire up a new issue. This one should stay for libclang related problems on Windows.

**Comment by niosus** [comment]
I have implemented a fallback option that just uses clang binary if it cannot find libclang. It passes tests on Linux, OSX and Windows for a simple auto-completion. Please try running the plugin again and verify if it works for you. 

The issues with libclang on all systems are still unresolved. Currently the only system that uses libclang in a stable way is Ubuntu 14.04 (16.04 too probably). Everything else will autocomplete using clang binary. This issue stays open until I find out what is happening.

**Comment by simonhaenisch** [comment]
```
DEBUG:EasyClangComplete.EasyClangComplete: starting async auto_complete at pos: 517
DEBUG:EasyClangComplete.plugin.clang_bin_complete: clang command: 
clang++ -cc1 -fsyntax-only -x c++ -std=c++11 -code-completion-at %user-local%\temp\test.cpp:32:9 %user-local%\temp\test.cpp -I%visual-studio%\VC\include -I%ms-sdks%\Windows\v7.1A\Include -I%llvm%\lib\clang\3.8.0\include -I%opencv%\build\include\opencv2 -I%current-dir%
DEBUG:EasyClangComplete.plugin.clang_bin_complete: started code complete for view 15
CRITICAL:EasyClangComplete.plugin.clang_bin_complete: 
DEBUG:EasyClangComplete.plugin.clang_bin_complete: code complete done in 0.06502604484558105 seconds
DEBUG:EasyClangComplete.plugin.clang_bin_complete: completions: []
DEBUG:EasyClangComplete.plugin.clang_bin_complete: reload completion tooltip
DEBUG:EasyClangComplete.EasyClangComplete: on_query_completions view id 15
```

This is what I get now when trying to trigger a completion for a Mat variable or doing `cv::` (I shortened the full paths for the -I arguments). Somehow it can't get any completions for OpenCV (maybe I use the wrong include dir?)... I use another framework and for that most completions work.

Another "bug" I get right now (I think it doesn't effect anything) is that the clang command gets the `-std=c++11` flag appended multiple times after some triggering (didn't figure out what it is):
```
clang++ -cc1 -fsyntax-only -x c++ -std=c++11 -std=c++11 -std=c++11 -code-completion-at ...
```

btw I like the way the tooltips are shown :+1:

**Comment by simonhaenisch** [comment]
btw that was when I used your last commit, not the current one... trying again

**Comment by niosus** [comment]
@simonhaenisch lets move discussions on OpenCV issues to #10 and the std bug to #9 

They are not fixed in the commit you are trying unfortunately. :)

**Comment by niosus** [comment]
Ok, I am determined to solve this. I have set up a test repo with an extremely simplified version of the code to complete. Find it [here](https://github.com/niosus/test-complete-plugin). There is one file `script.py` that tries to complete a test file. It works as expected with Python 3.3.5 (closest I have found to the one in sublime text) from Power Shell but from the sublime text causes this:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\igor\AppData\Roaming\Sublime Text 3\Packages\test_clang\script.py", line 21, in <module>
    tu = TU.from_source(filename=filename)
  File "C:\Users\igor\AppData\Roaming\Sublime Text 3\Packages\test_clang\clang\cindex38.py", line 2372, in from_source
    raise TranslationUnitLoadError("Error parsing translation unit.")
clang.cindex38.TranslationUnitLoadError: Error parsing translation unit.
```

Can you guys try it out if you have the same behavior? When I first copied this plugin into Packages folder it worked once from sublime text, but I cannot reproduce it anymore.

**Comment by niosus** [comment]
More issues related to libclang can be found in issue #41 I closed that issue to track all progress here.

**Comment by pl-ca** [comment]
When I launch ST3 after installing the plug-in I get an error related to some file not found. Am I missing something?

```
reloading plugin test-complete-plugin.script
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\script.py", line 14, in <module>
    clang_dir = ClangUtils.find_libclang_dir("clang++")
  File "C:\Users\Pierre-Louis\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\utils.py", line 62, in find_libclang_dir
    get_library_path_cmd).decode('utf8').strip()
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```

**Comment by niosus** [comment]
@pl-ca it is a new bug. I have moved it to another issue.

**Comment by niosus** [comment]
Unfortunately, it seems that for now this issue is impossible to fix. See [discussion](https://forum.sublimetext.com/t/ctypes-from-sublime-text-3-python-broken-on-windows/21490/15) with Sublime Text devs on the forum. So we will need to wait till python that is bundled with sublime text gets update to a newer version that does not have a bug that causes this issue.

**Comment by niosus** [comment]
I just want to report that there is great progress on this one. The test project had a bug where I used relative file path instead of an absolute one, so the test project works flawlessly on windows. Which means there is a bug somewhere in the code of the plugin.

I have been disabling parts of it to test what is not working and have found out that the thing that causes issues is actually error linting. I don't understand why just yet, but I am well on the way. Let's see. I hope to be done with this bug by the end of the week.

**Comment by rchl** [comment]
So the main python ctypes bug is now fixed in Sublime 3123, but I can't get suggestions to show up when using libclang.dll. I haven't investigated deeper yet. It might be something on my side or some minor bug.

**Comment by niosus** [comment]
Hmm... even after an update to a recent sublime text version this plugin still crashes when using libclang. but now it highlights errors first :) I guess we need another iteration on the test plugin.

**Comment by rchl** [comment]
I've tested it quite extensively with libclang and didn't see crashes. Used latest libclang release (3.9.0) from http://llvm.org/

**Comment by niosus** [comment]
Oh, wow. I will give it another try. I am still on clang 3.8.0. Should update probably. But if what you say will be the same on my side, this means this issue can eventually be closed! :+1:

**Comment by niosus** [comment]
Ok, so with clang 3.9 everything seems to work and does not crash. Which means I am closing this issue, and the next version is going to be 2.0. 🎆 :champagne: 🎉

**Comment by simonhaenisch** [comment]
Is there a way to use environment variables in include directives? I tried something like

```
-I%LIB_DIR%\\include
```

but it didn't work.

**Comment by DJviolin** [comment]
I'm getting the following errors with MSYS2 Clang 3.9.0:

```sh
$ python3 script.py
 clang could not find 'libclang.dll'
 clang could not find 'libclang.lib'
 no libclang found at all
Clang directory =  None
Platform:  ('64bit', 'WindowsPE')
Python version:  3.5.2
filename =  None
Traceback (most recent call last):
  File "script.py", line 21, in <module>
    tu = TU.from_source(filename=filename, args=clang_flags)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\cindex38.py", line 2344, in from_source
    index = Index.create()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\cindex38.py", line 2231, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\cindex38.py", line 144, in __get__
    value = self.wrapped(instance)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\cindex38.py", line 3594, in lib
    lib = self.get_cindex_library()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\test-complete-plugin\clang\cindex38.py", line 3615, in get_cindex_library
    library = cdll.LoadLibrary(self.get_filename())
  File "C:\msys64\mingw64\lib\python3.5\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\msys64\mingw64\lib\python3.5\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: bad argument type for built-in operation
```

When I used clang 3.9.2 binaries for MSVC from LLVM.org, the linting worked, but it's didn't found the header files, so I went back to MSYS2, but now EasyClangComplete not working.

**Comment by niosus** [comment]
I don't get what you mean by MSYS2. Also, if it didn't find the headers, you could have just added a correct path to your `common_flags`.

**Comment by DJviolin** [comment]
[MSYS2](https://msys2.github.io/) is a mingw wrapper like cygwin. It has it's own header files.. It's separated dev environment from MS visual studio.

```sh
$ clang --version
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:\msys64\mingw64\bin
```

**Comment by DJviolin** [comment]
I found the following files in these locations:

```sh
C:\msys64\mingw64\lib\libclang.a
C:\msys64\mingw64\lib\libclang.dll.a
```

At `C:\msys64\mingw64\bin\` location `libclang.dll` file is not presented in `MSYS2`. Maybe this helps something.

```sh
INFO:clang.utils: we are on 'Windows'
INFO:clang.utils: searching for: 'libclang.dll'
INFO:clang.utils: libclang search output = 'C:\msys64\mingw64\bin\'
DEBUG:clang.utils: real output: C:\msys64\mingw64\bin\
DEBUG:clang.utils: architecture: ('64bit', 'WindowsPE')
WARNING:clang.utils: clang could not find 'libclang.dll'
INFO:clang.utils: we are on 'Windows'
INFO:clang.utils: searching for: 'libclang.lib'
INFO:clang.utils: libclang search output = 'C:\msys64\mingw64\bin\'
DEBUG:clang.utils: real output: C:\msys64\mingw64\bin\
DEBUG:clang.utils: architecture: ('64bit', 'WindowsPE')
WARNING:clang.utils: clang could not find 'libclang.lib'
ERROR:clang.utils: no libclang found at all
```

**Comment by niosus** [comment]
Ok, this is something new to me. I have opened a new issue to track this: #194
