### ISSUE TITLE
Type completions missing after space

### ISSUE THREAD

**Issue by schreda** [niosus/EasyClangComplete#526]
There is following code:
```
#include <iostream>
#include <string>

int main() {
    std::cout << "ttt";
    return 0;
}
```

# System info: #
- Sublime Text version: `3 Build 3176`
- Which system are you on: `SuSE11`
- Clang version: `5.0.0`

# What happens:  #
ECC is giving an error on the << operator:
![capture](https://user-images.githubusercontent.com/1269774/47712391-e2bab900-dc37-11e8-9077-d2a05b82a2c1.PNG)
**This happens only when using libclang!**

Log: https://pastebin.com/FbDcFNQ4

**Comment by niosus** [comment]
Everything looks right to me in the log. What are your settings? This should be working out of the box.

**Comment by schreda** [comment]
That are my settings:

```
{
  "show_errors": true,
  "gutter_style": "dot",
  "hide_default_completions": true,
  "progress_style": "Moon",
  "use_libclang": true,
  "use_libclang_caching": true,
  "verbose" : false,
  "common_flags" : [
    "-I/usr/include"
  ],
}

```

**Comment by schreda** [comment]
These are the user settings. There are no project settings.

**Comment by niosus** [comment]
Ah, wait, you might need to specity where clang should search for additional includes, like in default settings. The setting with `clang_version` in it.

**Comment by schreda** [comment]
Tried to set it to the right path, but didn't work.

As i mentioned, this wrong behavior only occurs when i use libclang. If i set `use_libclang` to `false`, linting works fine!

**Comment by schreda** [comment]
I also saw, that without libclang i get more (all) autocompletion suggestions. I know, this is another issue but maybe both issues has something to do with libclang..

**Comment by niosus** [comment]
I think we already discussed this at some point. Libclang handles paths to standard lib differently from clang binary. At this point I don't know what exactly is different in your configuration, but it seems that the issues you are experiencing are related to it in some way. The logs don't show anything wrong with it. 

> Tried to set it to the right path, but didn't work.
Could you elaborate more? Can I see the log?

**Comment by schreda** [comment]
For my second issue here i recorded the different behavior of libclang and clang binary to autocomplete an enum. Maybe those issues are related to each other?
[https://schreda.com/nextcloud/index.php/s/wjHHgcnfeyWfFGR](https://schreda.com/nextcloud/index.php/s/wjHHgcnfeyWfFGR)

If you couldn't reproduce, tell me what steps/actions you need for a log file

**Comment by niosus** [comment]
This situation that you show in video is not really related to the plugin here. I am just a medium between libclang or clang and the end user. It seems that the plugin works still as expected, but libclang does not provide the needed information about the enum. And I don't think the way enums are used here are the intended way anyway, now that `enum class`, i.e. scoped enums are in the language. These work as expected.

**Comment by schreda** [comment]
I just did a quick look at the libclang handling in your code and saw something suspicious. I removed `ENUM_CONSTANT_DECL` from the `ignore_list` variable and now this issue is gone. Autocompletion for enums works for me now as espected for libclang!

Here is the patch i made: [https://github.com/schreda/EasyClangComplete/commit/28245878c00c131b751a31586cc4f2059b0c8569#diff-ba9fe772d3e476a72ff654b3619476a1](https://github.com/schreda/EasyClangComplete/commit/28245878c00c131b751a31586cc4f2059b0c8569#diff-ba9fe772d3e476a72ff654b3619476a1)

If this is a valid change, i will do a pull request

**Comment by niosus** [comment]
I don't think it is valid. The types should not appear if the trigger is different from either of the following: `['\t', ' ', '::']` and this is exactly what we achieve with the code you made changes to. The issue here seems to be that the current trigger that you have cannot be matched with space `" "`.

**Comment by niosus** [comment]
I have renamed this issue to reflect what I have fixed here. In the commit above I have fixed the way we have treated the trigger for completion. As for the original issue I cannot reproduce it. Please open a new one and append the log to it. Please follow the instructions in the body of the issue template.

**Comment by schreda** [comment]
Ah got it.
That's weird, because if i change `autocomplete_all ` to `enable` or use your new (fixed) version, i still have the same behavior.
If i comment out `self.cindex.CursorKind.ENUM_CONSTANT_DECL` from `bigger_ignore_list`, autocompletion find much more results... 
I know, this has only something to do with the trigger and not with the results from clang, but it behaves like it has...
