### ISSUE TITLE
MinGW doesn't seem to work out of the box

### ISSUE THREAD

**Issue by Glymse** [niosus/EasyClangComplete#684]
# System info: #
- Sublime Text version: `3.2.2`
- Which system are you on: `Windows 10`
- Clang version: `9.2.0`

# What happens:  #
When i include header files from the STL headers from minGW , the program stops working.

![image](https://user-images.githubusercontent.com/31343658/77634381-214dc380-6f51-11ea-8ed4-ebdc024ee534.png)

**Project settings:**
![image](https://user-images.githubusercontent.com/31343658/77635276-9a014f80-6f52-11ea-8b09-474e55ec5d52.png)

<details>
<summary>Log that illustrates the issue: </summary>
  
**Log**
```
<DPI mode: per-monitor v2
startup, version: 3211 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/WINDOWS/system32
packages path: /C/Users/jonas/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/jonas/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/jonas/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.292335
startup time: 0.335335
first paint time: 0.337335
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin ayu.activation
reloading plugin ayu.Icons
reloading plugin CppToolkit.cpp_refactor
reloading plugin CppToolkit.cpp_refactor_commands
reloading plugin HexViewer.hex_checksum
reloading plugin HexViewer.hex_common
reloading plugin HexViewer.hex_editor
reloading plugin HexViewer.hex_finder
reloading plugin HexViewer.hex_highlighter
reloading plugin HexViewer.hex_inspector
reloading plugin HexViewer.hex_notify
reloading plugin HexViewer.hex_viewer
reloading plugin HexViewer.hex_writer
reloading plugin HexViewer.sum_hashes
reloading plugin HexViewer.support
reloading plugin HexViewer.tiger
reloading plugin HexViewer.whirlpool
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin MoveTab.move_tab
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin ProjectEnvironment.ProjectEnvironment
plugins loaded
[ECC:DEBUG]:[settings_storage.py]:[need_reparse]:[MainThread]: settings complete
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[MainThread]: no settings for view 31. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: show_type_info             <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: use_libclang               <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[MainThread]: Settings sucessfully read...
[ECC:INFO]:[clang_utils.py]:[get_clang_version_str]:[MainThread]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[MainThread]: Populating common_flags with current variables.
[ECC:DEBUG]:[file.py]:[expand_all]:[MainThread]: Populated '$project_path/include' to '['D:\\Programmering\\C++\\Sublime\\First\\include']'
[ECC:DEBUG]:[file.py]:[expand_all]:[MainThread]: Populated '~/some_folder/*' to '['C:\\Users\\jonas\\some_folder\\*']'
[ECC:DEBUG]:[file.py]:[expand_all]:[MainThread]: Populated '/some/absolute/file.ext' to '['\\some\\absolute\\file.ext']'
[ECC:DEBUG]:[file.py]:[expand_all]:[MainThread]: Populated '$project_path/some/project/path/*' to '['D:\\Programmering\\C++\\Sublime\\First\\some\\project\\path\\*']'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[MainThread]: settings initialized for view: 31
[ECC:DEBUG]:[subl_bridge.py]:[get_view_lang]:[MainThread]: ECC does nothing for language syntax: 'Plain text'
[ECC:DEBUG]:[subl_bridge.py]:[get_view_lang]:[Dummy-6]: ECC does nothing for language syntax: 'Plain text'
[ECC:DEBUG]:[EasyClangComplete.py]:[on_close]:[MainThread]: closing view 31
[ECC:DEBUG]:[settings_manager.py]:[clear_for_view]:[MainThread]: clearing settings for view: 31
[ECC:DEBUG]:[EasyClangComplete.py]:[config_removed]:[MainThread]: removed config for id: 31
[ECC:DEBUG]:[view_config_manager.py]:[clear_for_view]:[Thread-7]: Trying to clear config for view: 31
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-6]: no settings for view 31. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: show_type_info             <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: use_libclang               <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Settings sucessfully read...
[ECC:INFO]:[clang_utils.py]:[get_clang_version_str]:[Dummy-6]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-6]: Populating common_flags with current variables.
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '$project_path/include' to '['D:\\Programmering\\C++\\Sublime\\First\\include']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '~/some_folder/*' to '['C:\\Users\\jonas\\some_folder\\*']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '/some/absolute/file.ext' to '['\\some\\absolute\\file.ext']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '$project_path/some/project/path/*' to '['D:\\Programmering\\C++\\Sublime\\First\\some\\project\\path\\*']'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-6]: settings initialized for view: 31
[ECC:ERROR]:[subl_bridge.py]:[get_view_syntax]:[Dummy-6]: error while getting current language: 'expected string or buffer'
[ECC:DEBUG]:[subl_bridge.py]:[get_view_lang]:[Dummy-6]: ECC does nothing for language syntax: 'None'
[ECC:DEBUG]:[settings_manager.py]:[settings_for_view]:[Dummy-6]: no settings for view 36. Reinitializing.
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Overriding settings by project ones if needed:
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Valid prefixes: ['ecc_', 'easy_clang_complete_']
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Reading settings...
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: show_type_info             <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: use_libclang               <-- 'False'
[ECC:DEBUG]:[settings_storage.py]:[__load_vars_from_settings]:[Dummy-6]: Settings sucessfully read...
[ECC:INFO]:[clang_utils.py]:[get_clang_version_str]:[Dummy-6]: Getting version from command: `clang++ -v`
[ECC:DEBUG]:[settings_storage.py]:[__populate_common_flags]:[Dummy-6]: Populating common_flags with current variables.
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '$project_path/include' to '['D:\\Programmering\\C++\\Sublime\\First\\include']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '~/some_folder/*' to '['C:\\Users\\jonas\\some_folder\\*']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '/some/absolute/file.ext' to '['\\some\\absolute\\file.ext']'
[ECC:DEBUG]:[file.py]:[expand_all]:[Dummy-6]: Populated '$project_path/some/project/path/*' to '['D:\\Programmering\\C++\\Sublime\\First\\some\\project\\path\\*']'
[ECC:DEBUG]:[settings_manager.py]:[__init_for_view]:[Dummy-6]: settings initialized for view: 36
[ECC:DEBUG]:[EasyClangComplete.py]:[on_activated_async]:[Dummy-6]: on_activated_async view id 36
[ECC:DEBUG]:[view_config_manager.py]:[load_for_view]:[Thread-7]: Generate new config for path: 36
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-7]: init completer based on clang from cmd
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-7]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete exists.
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-7]: Generating default flags from file 'ECC_temp_file.cpp' in folder 'c:\users\jonas\appdata\local\temp\EasyClangComplete'
[ECC:DEBUG]:[compiler_builtins.py]:[__generate_flags]:[Thread-7]: Generating new default flags with cmd: '['clang++', '-x', 'c++', '-std=c++17', '-c', 'ECC_temp_file.cpp', '-dM', '-v', '-E']'
[ECC:DEBUG]:[compiler_builtins.py]:[get_defines]:[Thread-7]: Got defines: ['-D_CPPRTTI=1', '-D_CPPUNWIND=1', '-D_HAS_CHAR16_T_LANGUAGE_SUPPORT=1', '-D_INTEGRAL_MAX_BITS=64', '-D_MSC_BUILD=1', '-D_MSC_EXTENSIONS=1', '-D_MSC_FULL_VER=191100000', '-D_MSC_VER=1911', '-D_MSVC_LANG=201703L', '-D_M_AMD64=100', '-D_M_X64=100', '-D_NATIVE_NULLPTR_SUPPORTED=1', '-D_NATIVE_WCHAR_T_DEFINED=1', '-D_RVALUE_REFERENCES_SUPPORTED=1', '-D_RVALUE_REFERENCES_V2_SUPPORTED=1', '-D_WCHAR_T_DEFINED=1', '-D_WIN32=1', '-D_WIN64=1', '-D__ATOMIC_ACQUIRE=2', '-D__ATOMIC_ACQ_REL=4', '-D__ATOMIC_CONSUME=1', '-D__ATOMIC_RELAXED=0', '-D__ATOMIC_RELEASE=3', '-D__ATOMIC_SEQ_CST=5', '-D__BIGGEST_ALIGNMENT__=16', '-D__BOOL_DEFINED=1', '-D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__', '-D__CHAR16_TYPE__=unsigned short', '-D__CHAR32_TYPE__=unsigned int', '-D__CHAR_BIT__=8', '-D__CLANG_ATOMIC_BOOL_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR16_T_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR32_T_LOCK_FREE=2', '-D__CLANG_ATOMIC_CHAR_LOCK_FREE=2', '-D__CLANG_ATOMIC_INT_LOCK_FREE=2', '-D__CLANG_ATOMIC_LLONG_LOCK_FREE=2', '-D__CLANG_ATOMIC_LONG_LOCK_FREE=2', '-D__CLANG_ATOMIC_POINTER_LOCK_FREE=2', '-D__CLANG_ATOMIC_SHORT_LOCK_FREE=2', '-D__CLANG_ATOMIC_WCHAR_T_LOCK_FREE=2', '-D__CONSTANT_CFSTRINGS__=1', '-D__DBL_DECIMAL_DIG__=17', '-D__DBL_DENORM_MIN__=4.9406564584124654e-324', '-D__DBL_DIG__=15', '-D__DBL_EPSILON__=2.2204460492503131e-16', '-D__DBL_HAS_DENORM__=1', '-D__DBL_HAS_INFINITY__=1', '-D__DBL_HAS_QUIET_NAN__=1', '-D__DBL_MANT_DIG__=53', '-D__DBL_MAX_10_EXP__=308', '-D__DBL_MAX_EXP__=1024', '-D__DBL_MAX__=1.7976931348623157e+308', '-D__DBL_MIN_10_EXP__=(-307)', '-D__DBL_MIN_EXP__=(-1021)', '-D__DBL_MIN__=2.2250738585072014e-308', '-D__DECIMAL_DIG__=__LDBL_DECIMAL_DIG__', '-D__DEPRECATED=1', '-D__FINITE_MATH_ONLY__=0', '-D__FLT_DECIMAL_DIG__=9', '-D__FLT_DENORM_MIN__=1.40129846e-45F', '-D__FLT_DIG__=6', '-D__FLT_EPSILON__=1.19209290e-7F', '-D__FLT_EVAL_METHOD__=0', '-D__FLT_HAS_DENORM__=1', '-D__FLT_HAS_INFINITY__=1', '-D__FLT_HAS_QUIET_NAN__=1', '-D__FLT_MANT_DIG__=24', '-D__FLT_MAX_10_EXP__=38', '-D__FLT_MAX_EXP__=128', '-D__FLT_MAX__=3.40282347e+38F', '-D__FLT_MIN_10_EXP__=(-37)', '-D__FLT_MIN_EXP__=(-125)', '-D__FLT_MIN__=1.17549435e-38F', '-D__FLT_RADIX__=2', '-D__FXSR__=1', '-D__GCC_ASM_FLAG_OUTPUTS__=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4=1', '-D__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8=1', '-D__INT16_C_SUFFIX__', '-D__INT16_FMTd__="hd"', '-D__INT16_FMTi__="hi"', '-D__INT16_MAX__=32767', '-D__INT16_TYPE__=short', '-D__INT32_C_SUFFIX__', '-D__INT32_FMTd__="d"', '-D__INT32_FMTi__="i"', '-D__INT32_MAX__=2147483647', '-D__INT32_TYPE__=int', '-D__INT64_C_SUFFIX__=LL', '-D__INT64_FMTd__="lld"', '-D__INT64_FMTi__="lli"', '-D__INT64_MAX__=9223372036854775807LL', '-D__INT64_TYPE__=long long int', '-D__INT8_C_SUFFIX__', '-D__INT8_FMTd__="hhd"', '-D__INT8_FMTi__="hhi"', '-D__INT8_MAX__=127', '-D__INT8_TYPE__=signed char', '-D__INTMAX_C_SUFFIX__=LL', '-D__INTMAX_FMTd__="lld"', '-D__INTMAX_FMTi__="lli"', '-D__INTMAX_MAX__=9223372036854775807LL', '-D__INTMAX_TYPE__=long long int', '-D__INTMAX_WIDTH__=64', '-D__INTPTR_FMTd__="lld"', '-D__INTPTR_FMTi__="lli"', '-D__INTPTR_MAX__=9223372036854775807LL', '-D__INTPTR_TYPE__=long long int', '-D__INTPTR_WIDTH__=64', '-D__INT_FAST16_FMTd__="hd"', '-D__INT_FAST16_FMTi__="hi"', '-D__INT_FAST16_MAX__=32767', '-D__INT_FAST16_TYPE__=short', '-D__INT_FAST32_FMTd__="d"', '-D__INT_FAST32_FMTi__="i"', '-D__INT_FAST32_MAX__=2147483647', '-D__INT_FAST32_TYPE__=int', '-D__INT_FAST64_FMTd__="lld"', '-D__INT_FAST64_FMTi__="lli"', '-D__INT_FAST64_MAX__=9223372036854775807LL', '-D__INT_FAST64_TYPE__=long long int', '-D__INT_FAST8_FMTd__="hhd"', '-D__INT_FAST8_FMTi__="hhi"', '-D__INT_FAST8_MAX__=127', '-D__INT_FAST8_TYPE__=signed char', '-D__INT_LEAST16_FMTd__="hd"', '-D__INT_LEAST16_FMTi__="hi"', '-D__INT_LEAST16_MAX__=32767', '-D__INT_LEAST16_TYPE__=short', '-D__INT_LEAST32_FMTd__="d"', '-D__INT_LEAST32_FMTi__="i"', '-D__INT_LEAST32_MAX__=2147483647', '-D__INT_LEAST32_TYPE__=int', '-D__INT_LEAST64_FMTd__="lld"', '-D__INT_LEAST64_FMTi__="lli"', '-D__INT_LEAST64_MAX__=9223372036854775807LL', '-D__INT_LEAST64_TYPE__=long long int', '-D__INT_LEAST8_FMTd__="hhd"', '-D__INT_LEAST8_FMTi__="hhi"', '-D__INT_LEAST8_MAX__=127', '-D__INT_LEAST8_TYPE__=signed char', '-D__INT_MAX__=2147483647', '-D__LDBL_DECIMAL_DIG__=17', '-D__LDBL_DENORM_MIN__=4.9406564584124654e-324L', '-D__LDBL_DIG__=15', '-D__LDBL_EPSILON__=2.2204460492503131e-16L', '-D__LDBL_HAS_DENORM__=1', '-D__LDBL_HAS_INFINITY__=1', '-D__LDBL_HAS_QUIET_NAN__=1', '-D__LDBL_MANT_DIG__=53', '-D__LDBL_MAX_10_EXP__=308', '-D__LDBL_MAX_EXP__=1024', '-D__LDBL_MAX__=1.7976931348623157e+308L', '-D__LDBL_MIN_10_EXP__=(-307)', '-D__LDBL_MIN_EXP__=(-1021)', '-D__LDBL_MIN__=2.2250738585072014e-308L', '-D__LITTLE_ENDIAN__=1', '-D__LONG_LONG_MAX__=9223372036854775807LL', '-D__LONG_MAX__=2147483647L', '-D__MMX__=1', '-D__NO_INLINE__=1', '-D__NO_MATH_INLINES=1', '-D__OBJC_BOOL_IS_BOOL=0', '-D__OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES=3', '-D__OPENCL_MEMORY_SCOPE_DEVICE=2', '-D__OPENCL_MEMORY_SCOPE_SUB_GROUP=4', '-D__OPENCL_MEMORY_SCOPE_WORK_GROUP=1', '-D__OPENCL_MEMORY_SCOPE_WORK_ITEM=0', '-D__ORDER_BIG_ENDIAN__=4321', '-D__ORDER_LITTLE_ENDIAN__=1234', '-D__ORDER_PDP_ENDIAN__=3412', '-D__PIC__=2', '-D__POINTER_WIDTH__=64', '-D__PRAGMA_REDEFINE_EXTNAME=1', '-D__PTRDIFF_FMTd__="lld"', '-D__PTRDIFF_FMTi__="lli"', '-D__PTRDIFF_MAX__=9223372036854775807LL', '-D__PTRDIFF_TYPE__=long long int', '-D__PTRDIFF_WIDTH__=64', '-D__REGISTER_PREFIX__', '-D__SCHAR_MAX__=127', '-D__SEG_FS=1', '-D__SEG_GS=1', '-D__SHRT_MAX__=32767', '-D__SIG_ATOMIC_MAX__=2147483647', '-D__SIG_ATOMIC_WIDTH__=32', '-D__SIZEOF_DOUBLE__=8', '-D__SIZEOF_FLOAT__=4', '-D__SIZEOF_INT128__=16', '-D__SIZEOF_INT__=4', '-D__SIZEOF_LONG_DOUBLE__=8', '-D__SIZEOF_LONG_LONG__=8', '-D__SIZEOF_LONG__=4', '-D__SIZEOF_POINTER__=8', '-D__SIZEOF_PTRDIFF_T__=8', '-D__SIZEOF_SHORT__=2', '-D__SIZEOF_SIZE_T__=8', '-D__SIZEOF_WCHAR_T__=2', '-D__SIZEOF_WINT_T__=2', '-D__SIZE_FMTX__="llX"', '-D__SIZE_FMTo__="llo"', '-D__SIZE_FMTu__="llu"', '-D__SIZE_FMTx__="llx"', '-D__SIZE_MAX__=18446744073709551615ULL', '-D__SIZE_TYPE__=long long unsigned int', '-D__SIZE_WIDTH__=64', '-D__SSE2_MATH__=1', '-D__SSE2__=1', '-D__SSE_MATH__=1', '-D__SSE__=1', '-D__STDCPP_DEFAULT_NEW_ALIGNMENT__=16ULL', '-D__STDC_HOSTED__=1', '-D__STDC_UTF_16__=1', '-D__STDC_UTF_32__=1', '-D__UINT16_C_SUFFIX__', '-D__UINT16_FMTX__="hX"', '-D__UINT16_FMTo__="ho"', '-D__UINT16_FMTu__="hu"', '-D__UINT16_FMTx__="hx"', '-D__UINT16_MAX__=65535', '-D__UINT16_TYPE__=unsigned short', '-D__UINT32_C_SUFFIX__=U', '-D__UINT32_FMTX__="X"', '-D__UINT32_FMTo__="o"', '-D__UINT32_FMTu__="u"', '-D__UINT32_FMTx__="x"', '-D__UINT32_MAX__=4294967295U', '-D__UINT32_TYPE__=unsigned int', '-D__UINT64_C_SUFFIX__=ULL', '-D__UINT64_FMTX__="llX"', '-D__UINT64_FMTo__="llo"', '-D__UINT64_FMTu__="llu"', '-D__UINT64_FMTx__="llx"', '-D__UINT64_MAX__=18446744073709551615ULL', '-D__UINT64_TYPE__=long long unsigned int', '-D__UINT8_C_SUFFIX__', '-D__UINT8_FMTX__="hhX"', '-D__UINT8_FMTo__="hho"', '-D__UINT8_FMTu__="hhu"', '-D__UINT8_FMTx__="hhx"', '-D__UINT8_MAX__=255', '-D__UINT8_TYPE__=unsigned char', '-D__UINTMAX_C_SUFFIX__=ULL', '-D__UINTMAX_FMTX__="llX"', '-D__UINTMAX_FMTo__="llo"', '-D__UINTMAX_FMTu__="llu"', '-D__UINTMAX_FMTx__="llx"', '-D__UINTMAX_MAX__=18446744073709551615ULL', '-D__UINTMAX_TYPE__=long long unsigned int', '-D__UINTMAX_WIDTH__=64', '-D__UINTPTR_FMTX__="llX"', '-D__UINTPTR_FMTo__="llo"', '-D__UINTPTR_FMTu__="llu"', '-D__UINTPTR_FMTx__="llx"', '-D__UINTPTR_MAX__=18446744073709551615ULL', '-D__UINTPTR_TYPE__=long long unsigned int', '-D__UINTPTR_WIDTH__=64', '-D__UINT_FAST16_FMTX__="hX"', '-D__UINT_FAST16_FMTo__="ho"', '-D__UINT_FAST16_FMTu__="hu"', '-D__UINT_FAST16_FMTx__="hx"', '-D__UINT_FAST16_MAX__=65535', '-D__UINT_FAST16_TYPE__=unsigned short', '-D__UINT_FAST32_FMTX__="X"', '-D__UINT_FAST32_FMTo__="o"', '-D__UINT_FAST32_FMTu__="u"', '-D__UINT_FAST32_FMTx__="x"', '-D__UINT_FAST32_MAX__=4294967295U', '-D__UINT_FAST32_TYPE__=unsigned int', '-D__UINT_FAST64_FMTX__="llX"', '-D__UINT_FAST64_FMTo__="llo"', '-D__UINT_FAST64_FMTu__="llu"', '-D__UINT_FAST64_FMTx__="llx"', '-D__UINT_FAST64_MAX__=18446744073709551615ULL', '-D__UINT_FAST64_TYPE__=long long unsigned int', '-D__UINT_FAST8_FMTX__="hhX"', '-D__UINT_FAST8_FMTo__="hho"', '-D__UINT_FAST8_FMTu__="hhu"', '-D__UINT_FAST8_FMTx__="hhx"', '-D__UINT_FAST8_MAX__=255', '-D__UINT_FAST8_TYPE__=unsigned char', '-D__UINT_LEAST16_FMTX__="hX"', '-D__UINT_LEAST16_FMTo__="ho"', '-D__UINT_LEAST16_FMTu__="hu"', '-D__UINT_LEAST16_FMTx__="hx"', '-D__UINT_LEAST16_MAX__=65535', '-D__UINT_LEAST16_TYPE__=unsigned short', '-D__UINT_LEAST32_FMTX__="X"', '-D__UINT_LEAST32_FMTo__="o"', '-D__UINT_LEAST32_FMTu__="u"', '-D__UINT_LEAST32_FMTx__="x"', '-D__UINT_LEAST32_MAX__=4294967295U', '-D__UINT_LEAST32_TYPE__=unsigned int', '-D__UINT_LEAST64_FMTX__="llX"', '-D__UINT_LEAST64_FMTo__="llo"', '-D__UINT_LEAST64_FMTu__="llu"', '-D__UINT_LEAST64_FMTx__="llx"', '-D__UINT_LEAST64_MAX__=18446744073709551615ULL', '-D__UINT_LEAST64_TYPE__=long long unsigned int', '-D__UINT_LEAST8_FMTX__="hhX"', '-D__UINT_LEAST8_FMTo__="hho"', '-D__UINT_LEAST8_FMTu__="hhu"', '-D__UINT_LEAST8_FMTx__="hhx"', '-D__UINT_LEAST8_MAX__=255', '-D__UINT_LEAST8_TYPE__=unsigned char', '-D__USER_LABEL_PREFIX__', '-D__VERSION__="Clang 9.0.0 (tags/RELEASE_900/final)"', '-D__WCHAR_MAX__=65535', '-D__WCHAR_TYPE__=unsigned short', '-D__WCHAR_UNSIGNED__=1', '-D__WCHAR_WIDTH__=16', '-D__WINT_MAX__=65535', '-D__WINT_TYPE__=unsigned short', '-D__WINT_UNSIGNED__=1', '-D__WINT_WIDTH__=16', '-D__amd64=1', '-D__amd64__=1', '-D__clang__=1', '-D__clang_major__=9', '-D__clang_minor__=0', '-D__clang_patchlevel__=0', '-D__clang_version__="9.0.0 (tags/RELEASE_900/final)"', '-D__code_model_small_=1', '-D__cplusplus=201703L', '-D__cpp_aggregate_bases=201603L', '-D__cpp_aggregate_nsdmi=201304L', '-D__cpp_alias_templates=200704L', '-D__cpp_aligned_new=201606L', '-D__cpp_attributes=200809L', '-D__cpp_binary_literals=201304L', '-D__cpp_capture_star_this=201603L', '-D__cpp_constexpr=201603L', '-D__cpp_decltype=200707L', '-D__cpp_decltype_auto=201304L', '-D__cpp_deduction_guides=201703L', '-D__cpp_delegating_constructors=200604L', '-D__cpp_digit_separators=201309L', '-D__cpp_enumerator_attributes=201411L', '-D__cpp_exceptions=199711L', '-D__cpp_fold_expressions=201603L', '-D__cpp_generic_lambdas=201304L', '-D__cpp_guaranteed_copy_elision=201606L', '-D__cpp_hex_float=201603L', '-D__cpp_if_constexpr=201606L', '-D__cpp_impl_destroying_delete=201806L', '-D__cpp_inheriting_constructors=201511L', '-D__cpp_init_captures=201304L', '-D__cpp_initializer_lists=200806L', '-D__cpp_inline_variables=201606L', '-D__cpp_lambdas=200907L', '-D__cpp_namespace_attributes=201411L', '-D__cpp_nested_namespace_definitions=201411L', '-D__cpp_noexcept_function_type=201510L', '-D__cpp_nontype_template_args=201411L', '-D__cpp_nontype_template_parameter_auto=201606L', '-D__cpp_nsdmi=200809L', '-D__cpp_range_based_for=201603L', '-D__cpp_raw_strings=200710L', '-D__cpp_ref_qualifiers=200710L', '-D__cpp_return_type_deduction=201304L', '-D__cpp_rtti=199711L', '-D__cpp_rvalue_references=200610L', '-D__cpp_static_assert=201411L', '-D__cpp_structured_bindings=201606L', '-D__cpp_template_auto=201606L', '-D__cpp_threadsafe_static_init=200806L', '-D__cpp_unicode_characters=200704L', '-D__cpp_unicode_literals=200710L', '-D__cpp_user_defined_literals=200809L', '-D__cpp_variable_templates=201304L', '-D__cpp_variadic_templates=200704L', '-D__cpp_variadic_using=201611L', '-D__k8=1', '-D__k8__=1', '-D__llvm__=1', '-D__pic__=2', '-D__seg_fs=__attribute__((address_space(257)))', '-D__seg_gs=__attribute__((address_space(256)))', '-D__tune_k8__=1', '-D__x86_64=1', '-D__x86_64__=1']
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-7]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-7]: Tokenizing: ['-x', 'c++', '-std=c++17', '-IC:\\Program Files\\LLVM\\lib\\clang\\9.0.0\\include']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Source
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: [cmake]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'CMakeLists.txt' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: No CMakeLists.txt file with 'project' in it found.
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'compile_commands.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-7]: [CppProperties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-7]: [CppProperties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'CppProperties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-7]: [c_cpp_properties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-7]: [c_cpp_properties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'c_cpp_properties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-7]: [clang_complete_file]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-7]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching '.clang_complete' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Merge
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-7]: lang flags: [(-x c++), (-std=c++17), (-IC:\Program Files\LLVM\lib\clang\9.0.0\include)]
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Appending and filtering flags with ignore patterns: ['some_flag_pattern*', '-W_other_pattern_$project_path*']
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-7]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89 exists.
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-7]: clang command: 
'clang++' '-c' '-fsyntax-only' '-x' 'c++' '-std=c++17' '-I' 'C:\Program Files\LLVM\lib\clang\9.0.0\include' '-I' 'D:\Programmering\C++\Sublime\First\include' '-I' 'C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++' '-I' 'C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++\mingw32\bits' 'c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp'
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-7]: Command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-7]: Command output: 
In file included from c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp:1:

C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++\iostream:38:10: fatal error: 'bits/c++config.h' file not found

#include <bits/c++config.h>

         ^~~~~~~~~~~~~~~~~~

1 error generated.


[ECC:DEBUG]:[bin_complete.py]:[update]:[Thread-7]: rebuilding done in 0.12087202072143555 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-7]: Generating error regions for view 36
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-7]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-7]: Showing error regions: []
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-7]: Showing warning regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-7]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x03FF6750>
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config exists for view: 36
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-6]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x03FF6750>
[ECC:DEBUG]:[popup_error_vis.py]:[show_popup_if_needed]:[Dummy-6]: No error regions for row: 11
[ECC:DEBUG]:[EasyClangComplete.py]:[on_post_save_async]:[Dummy-6]: saving view: 36
[ECC:DEBUG]:[view_config_manager.py]:[load_for_view]:[Thread-7]: Config exists for path: 36
[ECC:INFO]:[view_config.py]:[__init_completer]:[Thread-7]: init completer based on clang from cmd
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-7]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete exists.
[ECC:DEBUG]:[compiler_builtins.py]:[__init__]:[Thread-7]: Generating default flags from file 'ECC_temp_file.cpp' in folder 'c:\users\jonas\appdata\local\temp\EasyClangComplete'
[ECC:DEBUG]:[compiler_builtins.py]:[__generate_flags]:[Thread-7]: Using cached default flags.
[ECC:DEBUG]:[view_config.py]:[__get_default_flags]:[Thread-7]: Tokeninzing default flags
[ECC:DEBUG]:[flag.py]:[tokenize_list]:[Thread-7]: Tokenizing: ['-x', 'c++', '-std=c++17', '-IC:\\Program Files\\LLVM\\lib\\clang\\9.0.0\\include']
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Common
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Source
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: [cmake]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: [cmake]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'CMakeLists.txt' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[cmake_file.py]:[get_flags]:[Thread-7]: No CMakeLists.txt file with 'project' in it found.
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'compile_commands.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-7]: [CppProperties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[CppProperties.py]:[get_flags]:[Thread-7]: [CppProperties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'CppProperties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-7]: [c_cpp_properties]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[c_cpp_properties.py]:[get_flags]:[Thread-7]: [c_cpp_properties]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching 'c_cpp_properties.json' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-7]: [clang_complete_file]:[get]: for file D:\Programmering\C++\Sublime\First\src\main.cpp
[ECC:DEBUG]:[flags_file.py]:[get_flags]:[Thread-7]: [clang_complete_file]:[cached]: 'None'
[ECC:DEBUG]:[file.py]:[search]:[Thread-7]: Searching '.clang_complete' file in: SearchScope: from_folder: D:\Programmering\C++\Sublime\First\src, to_folder: D:\\Programmering\\C++\\Sublime\\First
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Merge
[ECC:DEBUG]:[view_config.py]:[__merge_flags]:[Thread-7]: lang flags: [(-x c++), (-std=c++17), (-IC:\Program Files\LLVM\lib\clang\9.0.0\include)]
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-7]: Appending and filtering flags with ignore patterns: ['some_flag_pattern*', '-W_other_pattern_$project_path*']
[ECC:DEBUG]:[view_config.py]:[needs_update]:[Thread-7]: view config needs no update.
[ECC:DEBUG]:[file.py]:[is_unchanged]:[Thread-7]: never seen file 'D:\Programmering\C++\Sublime\First\src\main.cpp' before. Updating.
[ECC:DEBUG]:[view_config.py]:[update_if_needed]:[Thread-7]: config updates existing completer.
[ECC:DEBUG]:[file.py]:[get_temp_dir]:[Thread-7]: Folder c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89 exists.
[ECC:DEBUG]:[bin_complete.py]:[run_clang_command]:[Thread-7]: clang command: 
'clang++' '-c' '-fsyntax-only' '-x' 'c++' '-std=c++17' '-I' 'C:\Program Files\LLVM\lib\clang\9.0.0\include' '-I' 'D:\Programmering\C++\Sublime\First\include' '-I' 'C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++' '-I' 'C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++\mingw32\bits' 'c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp'
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-7]: Command finished with code: 1
[ECC:DEBUG]:[tools.py]:[run_command]:[Thread-7]: Command output: 
In file included from c:\users\jonas\appdata\local\temp\EasyClangComplete\34d682678d691c38694ff08cd9e7fa89\main.cpp:1:

C:\MinGW\lib\gcc\mingw32\9.2.0\include\c++\iostream:38:10: fatal error: 'bits/c++config.h' file not found

#include <bits/c++config.h>

         ^~~~~~~~~~~~~~~~~~

1 error generated.


[ECC:DEBUG]:[bin_complete.py]:[update]:[Thread-7]: rebuilding done in 0.12466597557067871 seconds
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-7]: Generating error regions for view 36
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-7]: Removing old error regions
[ECC:DEBUG]:[popup_error_vis.py]:[generate]:[Thread-7]: 1 error regions ready
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-7]: Showing error regions: []
[ECC:DEBUG]:[popup_error_vis.py]:[show_errors]:[Thread-7]: Showing warning regions: []
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-7]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x03FF6750>
Package Control: Skipping automatic upgrade, last run at 2020-03-26 11:07:16, next run at 2020-03-26 12:07:16 or after
[ECC:DEBUG]:[subl_bridge.py]:[is_valid_view]:[Dummy-6]: view file_name is None
>
```

</details>

**Comment by Glymse** [comment]
**UPDATE: I FIXED THE PROBLEM!**
It had nothing to do with my configuration,
eventually after searching for the problem the last few days i installed visual studio, and now it seems to work.

**Comment by niosus** [comment]
So, when you have visual studio installed the plugin should definitely work out of the box, as this is the thing that we test in the unit tests. I still don't like that MinGW doesn't work out of the box. Maybe if I find the time, I will create another Windows CI build that will check the plugin against mingw installation...

**Comment by thisisleobro** [comment]
Any updates on this??

**Comment by niosus** [comment]
Nope, sorry. I don't have enough time lately. Also, fixing bugs on Windows takes much more time for me as this is not the system I am very familiar with. If anyone wants to chime in and create an appropriate job (see `appveyor.yml` file in the repo) I am happy to review a PR for that.
