### ISSUE TITLE
Linting through clang binary spams the console with errors

### ISSUE THREAD

**Issue by rchl** [niosus/EasyClangComplete#74]
When using clang binary for linting (haven't tried libclang), the console shows the clang command output whenever there is some error in the code. For example:

> INFO:EasyClangComplete.plugin.completion.base_complete: clang process finished with code: 1
> INFO:EasyClangComplete.plugin.completion.base_complete: clang process output:
> [code]

As errors are expected, those should not be printed. Only unexpected errors when running BaseCompleter.run_command() should be printed.

**Comment by niosus** [comment]
Yes, makes sense! I think it slipped into the code during some debugging session of mine. I will change it from `INFO` to `DEBUG`.

**Comment by niosus** [comment]
Oh, actually, I think it was already fixed in master quite a while ago. I just haven't had the time to create a release yet, as the functionality change is significant and I don't want to break things for people happily using the plugin :)

**Comment by rchl** [comment]
I'm running the plugin from local checkout on master branch and reported it against that version. So I don't think that's fixed.

**Comment by niosus** [comment]
Indeed. Sorry, confused it with other place. Should be fixed now.
